// DO NOT MODIFY AUTO-GENERATED BY PB-WALKER
use mysql_async::prelude::*;
use mysql_async::{FromRowError, OptsBuilder, Params, Row, Pool};
use mysql_common::row::ColumnIndex;

use mysql_common::value::Value;
use crate::mysql_shared::*;

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct {{ .TableNameCamel }}  { // {{ .TableName }}
{{- range .Columns }}
    pub {{ .ColumnName }}: {{ .RustType }},
{{- end }}
}

impl FromRow for {{ .TableNameCamel }} {
    fn from_row_opt(row: Row) -> Result<Self, FromRowError>
    where
        Self: Sized,
    {
        Ok({{ .TableNameCamel }}  {
        {{- range .Columns }}
            {{ .ColumnName }}: row.get({{ .GetColIndex }}).unwrap_or_default(),
        {{- end }}
        })
    }
}

{{- $tableScheme := .SchemeTable }}

impl {{ .TableNameCamel }} {

{{- if .AutoIncrKey }}
    pub async fn insert(&self, spool: &SPool) -> Result<{{ .TableNameCamel }},MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"INSERT INTO {:}.{{ .TableName }} ({{ colnames .Columns .AutoIncrKey.ColumnName }}) VALUES ({{ colvals_dollar . .Columns .AutoIncrKey.ColumnName }})",&spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamNoneIncrKeys }}]);

        let qr = conn.exec_iter(
            query, p
        ).await?;

        let mut cp = self.clone();
        cp.{{ .AutoIncrKey.ColumnName }} = qr.last_insert_id().unwrap() as {{ .AutoIncrKey.RustType }};
        Ok(cp)
    }
{{ else }}
    pub async fn insert(&self, spool: &SPool) -> Result<{{ .TableNameCamel }},MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"INSERT INTO {:}.{{ .TableName }} ({{ colnames .Columns }}) VALUES ({{ colvals_dollar . .Columns }})",&spool.database);
        let p = Params::Positional(vec![{{ .GetRustParam }}]);

        conn.exec_iter(
            query, p
        ).await?;

        let cp = self.clone();
        Ok(cp)
    }
{{- end }}

    // todo add replace with coping insert after it's complete

    pub async fn update(&self, spool: &SPool) -> Result<(),MyError> {
        let mut conn = spool.pool.get_conn().await?;
        let query = format!(r"UPDATE `{:}`.{{ .TableName }}` SET {{ .GetRustUpdateFrag }} WHERE {{ .GetRustUpdateKeysWhereFrag }} ", &spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamNoPrimaryKeys }}, {{ .GetRustParamPrimaryKeys }} ]);

        let qr = conn.exec_iter(
            query, p
        ).await?;

        Ok(())
    }

    pub async fn delete(&self, spool: &SPool) -> Result<(),MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"DELETE FROM `{:}`.{{ .TableName }}` WHERE {{ .GetRustUpdateKeysWhereFrag }} ", &spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamPrimaryKeys }}]);

        conn.exec_drop(
            query, p
        ).await?;

        Ok(())
    }
}


#[derive(Default, Debug)]
pub struct {{ .TableNameCamel }}Selector {
    q: TQuery
}

impl {{ .TableNameCamel }}Selector {
    pub fn new() -> Self {
        {{ .TableNameCamel }}Selector::default()
    }

    pub fn limit(&mut self, size: u32) -> &mut Self {
        self.q.limit = size;
        self
    }

    pub fn offset(&mut self, size: u32) -> &mut Self {
        self.q.offset = size;
        self
    }

    pub fn select_all(&mut self) -> &mut Self {
        // Default is select *
        self
    }

    //each column select
    {{- range .Columns }}
    pub fn select_{{ .ColumnName }}(&mut self) -> &mut Self {
        self.q.select_cols.push("{{.ColumnName}}");
        self
    }
    {{ end }}

    fn _to_cql(&self) ->  (String, Vec<Value>)  {
        let cql_select = if self.q.select_cols.is_empty() {
            "*".to_string()
        } else {
            self.q.select_cols.join(", ")
        };

        let mut cql_query = format!("SELECT {} FROM {{.SchemeTable}}", cql_select);

        let (cql_where, where_values) = _get_where(self.q.wheres.clone());

        if where_values.len() > 0 {
            cql_query.push_str(&format!(" WHERE {}",&cql_where));
        }

        if self.q.order_by.len() > 0 {
            let cql_orders = self.q.order_by.join(", ");
            cql_query.push_str( &format!(" ORDER BY {}", &cql_orders));
        };

        if self.q.limit != 0  {
            cql_query.push_str(&format!(" LIMIT {} ", self.q.limit));
        };

        if self.q.offset != 0  {
            cql_query.push_str(&format!(" OFFSET {} ", self.q.offset));
        };

        (cql_query, where_values)
    }

    pub async fn _get_rows_with_size(&mut self, session: &Pool, size: i64) -> Result<Vec<{{ .TableNameCamel }}>, MyError>   {
        let mut conn = session.get_conn().await?;
        let(cql_query, query_values) = self._to_cql();

        println!("{} - {:?}", &cql_query, &query_values);

        let p = Params::Positional(query_values);

        let query_result = conn
            .exec_map(
                cql_query,p,
                |obj: {{ .TableNameCamel }}| obj
            ).await?;

        Ok(query_result)
    }

    pub async fn get_rows(&mut self, session: &Pool) -> Result<Vec<{{ .TableNameCamel }}>, MyError>{
        self._get_rows_with_size(session,-1).await
    }

    pub async fn get_row(&mut self, session: &Pool) -> Result<{{ .TableNameCamel }}, MyError>{
        let rows = self._get_rows_with_size(session,1).await?;

        let opt = rows.get(0);
        match opt {
            Some(row) => Ok(row.to_owned()),
            None => Err(MyError::NotFound)
        }
    }

    // Modifiers

    {{ .GetRustSelectorOrders }}

    {{ .GetRustWheresTmplOut }}

    {{ .GetRustWhereInsTmplOut }}

}
