// DO NOT MODIFY AUTO-GENERATED BY PB-WALKER
use mysql_async::prelude::*;
use mysql_async::{FromRowError, OptsBuilder, Params, Row, Pool};
use mysql_common::row::ColumnIndex;

use mysql_common::value::Value;
use crate::mysql_shared::*;

#[derive(Default, Clone, PartialEq, Eq, Debug)]
pub struct {{ .TableNameCamel }}  { // {{ .TableName }}
{{- range .Columns }}
    pub {{ .ColumnName }}: {{ .RustType }},
{{- end }}
}

impl FromRow for {{ .TableNameCamel }} {
    fn from_row_opt(row: Row) -> Result<Self, FromRowError>
    where
        Self: Sized,
    {
        Ok({{ .TableNameCamel }}  {
        {{- range .Columns }}
            {{ .ColumnName }}: row.get({{ .GetColIndex }}).unwrap_or_default(),
        {{- end }}
        })
    }
}

{{- $tableScheme := .SchemeTable }}

impl {{ .TableNameCamel }} {

{{- if .AutoIncrKey }}
    pub async fn insert(&self, spool: &SPool) -> Result<{{ .TableNameCamel }},MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"INSERT INTO {:}.{{ .TableName }} ({{ colnames .Columns .AutoIncrKey.ColumnName }}) VALUES ({{ colvals_dollar . .Columns .AutoIncrKey.ColumnName }})",&spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamNoneIncrKeys }}]);

        let qr = conn.exec_iter(
            query, p
        ).await?;

        let mut cp = self.clone();
        cp.{{ .AutoIncrKey.ColumnName }} = qr.last_insert_id().unwrap() as {{ .AutoIncrKey.RustType }};
        Ok(cp)
    }
{{ else }}
    pub async fn insert(&self, spool: &SPool) -> Result<{{ .TableNameCamel }},MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"INSERT INTO {:}.{{ .TableName }} ({{ colnames .Columns }}) VALUES ({{ colvals_dollar . .Columns }})",&spool.database);
        let p = Params::Positional(vec![{{ .GetRustParam }}]);

        conn.exec_iter(
            query, p
        ).await?;

        let cp = self.clone();
        Ok(cp)
    }
{{- end }}

    // todo add replace with coping insert after it's complete

    pub async fn update(&self, spool: &SPool) -> Result<(),MyError> {
        let mut conn = spool.pool.get_conn().await?;
        let query = format!(r"UPDATE `{:}`.{{ .TableName }}` SET {{ .GetRustUpdateFrag }} WHERE {{ .GetRustUpdateKeysWhereFrag }} ", &spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamNoPrimaryKeys }}, {{ .GetRustParamPrimaryKeys }} ]);

        let qr = conn.exec_iter(
            query, p
        ).await?;

        Ok(())
    }

    pub async fn delete(&self, spool: &SPool) -> Result<(),MyError> {
        let mut conn = spool.pool.get_conn().await?;

        let query = format!(r"DELETE FROM `{:}`.{{ .TableName }}` WHERE {{ .GetRustUpdateKeysWhereFrag }} ", &spool.database);
        let p = Params::Positional(vec![{{ .GetRustParamPrimaryKeys }}]);

        conn.exec_drop(
            query, p
        ).await?;

        Ok(())
    }
}


#[derive(Default, Debug)]
pub struct {{ .TableNameCamel }}Selector {
    q: TQuery
}

impl {{ .TableNameCamel }}Selector {
    pub fn new() -> Self {
        {{ .TableNameCamel }}Selector::default()
    }

    pub fn limit(&mut self, size: u32) -> &mut Self {
        self.q.limit = size;
        self
    }

    pub fn offset(&mut self, size: u32) -> &mut Self {
        self.q.offset = size;
        self
    }

    pub fn select_all(&mut self) -> &mut Self {
        // Default is select *
        self
    }

    //each column select
    {{- range .Columns }}
    pub fn select_{{ .ColumnName }}(&mut self) -> &mut Self {
        self.q.select_cols.push("{{.ColumnName}}");
        self
    }
    {{ end }}

    pub async fn _get_rows_with_size(&mut self, session: &SPool, size: i64) -> Result<Vec<{{ .TableNameCamel }}>, MyError>   {
        let mut conn = session.pool.get_conn().await?;
        let(cql_query, query_values) = self.q._to_sql_selector();

        println!("{} - {:?}", &cql_query, &query_values);

        let p = Params::Positional(query_values);

        let query_result = conn
            .exec_map(
                cql_query,p,
                |obj: {{ .TableNameCamel }}| obj
            ).await?;

        Ok(query_result)
    }

    pub async fn get_rows(&mut self, session: &SPool) -> Result<Vec<{{ .TableNameCamel }}>, MyError>{
        self._get_rows_with_size(session,-1).await
    }

    pub async fn get_row(&mut self, session: &SPool) -> Result<{{ .TableNameCamel }}, MyError>{
        let rows = self._get_rows_with_size(session,1).await?;

        let opt = rows.get(0);
        match opt {
            Some(row) => Ok(row.to_owned()),
            None => Err(MyError::NotFound)
        }
    }

    // Modifiers
    {{ .GetRustSelectorOrders }}
    {{ .GetRustWheresTmplOut }}
    {{ .GetRustWhereInsTmplOut }}
}

{{- $deleterType := printf "%s_Deleter" .TableNameCamel }}

#[derive(Default, Debug)]
pub struct {{ $deleterType }} {
    q: TQuery
}

impl {{ $deleterType }} {
    pub fn new() -> Self {
        {{ $deleterType }}::default()
    }

    //each column delete
    {{- range .Columns }}
    pub fn delete_{{ .ColumnName }}(&mut self) -> &mut Self {
        self.q.delete_cols.push("{{.ColumnName}}");
        self
    }
    {{ end }}

    pub async fn delete(&mut self, session: SPool) -> Result<(),MyError> {
        delete_rows(&self.q, session).await
        /*let mut conn = session.pool.get_conn().await?;
        let del_col = self.q.delete_cols.join(", ");

        let (cql_where, where_values) = _get_where(self.q.wheres.clone());

        let cql_query = format!("DELETE {} FROM `twitter`.`tweet` WHERE {}", del_col, cql_where);

        let p = Params::Positional(where_values);

        println!("{} - {:?}", &cql_query, &p);

        let query_result = conn.exec_drop(cql_query,p,).await?;

        Ok(())*/
    }

    pub fn delete(&mut self, session: SPool) -> Result<(),CWError> {
        let del_col = self.q.delete_cols.join(", ");

        let  mut where_str = vec![];
        let mut where_arr = vec![];

        for w in self.q.wheres.clone() {
            where_str.push(w.condition);
            where_arr.push(w.args)
        }

        let where_str = where_str.join(" ");

        let cql_query = format!("DELETE {} FROM {{ .SchemeTable }} WHERE {}", del_col, where_str);

        let query_values = QueryValues::SimpleValues(where_arr);
        println!("{} - {:?}", &cql_query, &query_values);

        session.query_with_values(cql_query, query_values)?;

        Ok(())
    }

    {{ .GetRustWheresTmplOut }}

    {{ .GetRustWhereInsTmplOut }}
}